### ISSUE TITLE
var 'res'

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_prefs#12]
```
Python 3.8.5
Init: cuda_console_complete
Init: cuda_hilite_occurrences
Loaded session: "history session.json", 10ms, 1 file(s)
Startup: 160ms, plugins: 20ms (console_complete 16ms, hilite_occurrences 12ms)
Init: cuda_prefs
Init: cudatext
Traceback (most recent call last):
  File "/home/user/cuda/cuda/app/py/cuda_prefs/cd_opts_dlg.py", line 938, in dlg_cuda_options
    self._dlg_opt()
  File "/home/user/cuda/cuda/app/py/cuda_prefs/cd_opts_dlg.py", line 944, in _dlg_opt
    opted.show(_('CudaText options lite'))
  File "/home/user/cuda/cuda/app/py/cuda_prefs/cd_opts_dlg.py", line 469, in show
    self.dlg.show()
  File "/home/user/cuda/cuda/app/py/cuda_prefs/dlg.py", line 506, in show
    self.set_filter(_filter_val)
  File "/home/user/cuda/cuda/app/py/cuda_prefs/dlg.py", line 899, in set_filter
    self.update_list(opts)
  File "/home/user/cuda/cuda/app/py/cuda_prefs/dlg.py", line 825, in update_list
    col_values = [str(self.optman.get_opt_active_value(op, is_ui=True)) for op in opts]
  File "/home/user/cuda/cuda/app/py/cuda_prefs/dlg.py", line 825, in <listcomp>
    col_values = [str(self.optman.get_opt_active_value(op, is_ui=True)) for op in opts]
  File "/home/user/cuda/cuda/app/py/cuda_prefs/cd_opts_dlg.py", line 853, in get_opt_active_value
    return (scope, res)  if with_scope else  res
UnboundLocalError: local variable 'res' referenced before assignment
ERROR: Exception in CudaText for dlg_cuda_options: UnboundLocalError: local variable 'res' referenced before assignment
```

**Comment by halfbrained** [comment]
Should be fixed. 

Old Options Editor talks about 'not CudaText standard option', what's that? :)

**Comment by Alexey-T** [comment]
an option written by Kv's plugins to user.json

**Comment by Alexey-T** [comment]
or maybe this too https://wiki.freepascal.org/CudaText#File_types_config
