### ISSUE TITLE
still unboundLocalError

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_prefs#17]
```
Python 3.8.5
Init: cuda_hilite_occurrences
Init: cuda_lsp
Init: cuda_tab_icons
Loaded session: "history session.json", 10ms, 2 file(s)
LSP: starting server - Python; root: None
Startup: 300ms, plugins: 160ms (hilite_occurrences 26ms, lsp 137ms, tab_icons 3ms)
Init: cudatext
Init: cuda_prefs
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_prefs/cd_opts_dlg.py", line 939, in dlg_cuda_options
    self._dlg_opt()
  File "/home/user/.config/cudatext/py/cuda_prefs/cd_opts_dlg.py", line 945, in _dlg_opt
    opted.show(_('CudaText options lite'))
  File "/home/user/.config/cudatext/py/cuda_prefs/cd_opts_dlg.py", line 469, in show
    self.dlg.show()
  File "/home/user/.config/cudatext/py/cuda_prefs/dlg.py", line 545, in show
    self.set_filter(_filter_val)
  File "/home/user/.config/cudatext/py/cuda_prefs/dlg.py", line 938, in set_filter
    self.update_list(opts)
  File "/home/user/.config/cudatext/py/cuda_prefs/dlg.py", line 864, in update_list
    col_values = [str(self.optman.get_opt_active_value(op, is_ui=True)) for op in opts]
  File "/home/user/.config/cudatext/py/cuda_prefs/dlg.py", line 864, in <listcomp>
    col_values = [str(self.optman.get_opt_active_value(op, is_ui=True)) for op in opts]
  File "/home/user/.config/cudatext/py/cuda_prefs/cd_opts_dlg.py", line 854, in get_opt_active_value
    return (scope, res)  if with_scope else  res
UnboundLocalError: local variable 'res' referenced before assignment
ERROR: Exception in CudaText for dlg_cuda_options: UnboundLocalError: local variable 'res' referenced before assignment
```

**Comment by halfbrained** [comment]
Fixed, shouldn't happen anymore. And added a more informative exception just in case.
