### ISSUE TITLE
Reset button is not working in W10

### ISSUE THREAD

**Issue by JairoMartinezA** [halfbrained/cuda_prefs#20]
![image](https://user-images.githubusercontent.com/5806694/118300743-e5a0f080-b4a7-11eb-87a0-ff2e15022f49.png)

**Comment by JairoMartinezA** [comment]
I mean, Reset button needs to automatically change the value in the textbox, currently I need to press Apply or Close to get the confirmation dialog:
![image](https://user-images.githubusercontent.com/5806694/118301779-12093c80-b4a9-11eb-95a4-01b4e6487fa3.png)

**Comment by halfbrained** [comment]
Well that was a major oversight :) fixed

**Comment by JairoMartinezA** [comment]
With same option and with updated git code, after press Reset, the value changes to empty and after press OK, after confirmation dialog the console prints:

    TypeError: an integer is required (got type NoneType)

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "C:\Users\Jairo Martinez\Downloads\Apps\Cudatext\py\cuda_prefs\cd_opts_dlg.py", line 941, in dlg_cuda_options
        self._dlg_opt()
      File "C:\Users\Jairo Martinez\Downloads\Apps\Cudatext\py\cuda_prefs\cd_opts_dlg.py", line 947, in _dlg_opt
        opted.show(_('CudaText options lite'))
      File "C:\Users\Jairo Martinez\Downloads\Apps\Cudatext\py\cuda_prefs\cd_opts_dlg.py", line 469, in show
        self.dlg.show()
      File "C:\Users\Jairo Martinez\Downloads\Apps\Cudatext\py\cuda_prefs\dlg.py", line 584, in show
        dlg_proc(self.h, DLG_FREE)
      File "C:\Users\Jairo Martinez\Downloads\Apps\Cudatext\py\cudatext.py", line 1218, in dlg_proc
        res = ct.dlg_proc(id_dialog, id_action, to_str(prop), index, index2, name)
    SystemError: <built-in function dlg_proc> returned a result with an error set
    ERROR: Exception in CudaText for dlg_cuda_options: SystemError: <built-in function dlg_proc> returned a result with an error set

**Comment by Alexey-T** [comment]
maybe better to post this as separate report, so @halfbrained won't miss it.
