### ISSUE TITLE
after some clicks in UI listbox I got

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_prefs#8]
```
Init: cuda_prefs
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cudatext.py", line 1191, in _dlg_proc_callback_proxy
    return _live[info](id_dlg, id_ctl, data=data)
  File "/home/user/.config/cudatext/py/cuda_prefs/dlg.py", line 1022, in _on_opt_click
    new_scope_name = self._scope_captions[new_scope]
KeyError: 'f'
ERROR: Exception in CudaText for cudatext._dlg_proc_callback_proxy: KeyError: 'f'
```

**Comment by Alexey-T** [comment]
@jairoMartinezA
@miroslavmatas
@kvichans if you have time to test this plugin, it's good.

**Comment by halfbrained** [comment]
Oh, that's for a tab without a file? I'll get right on that :)

**Comment by Alexey-T** [comment]
>that's for a tab without a file?

yes

**Comment by halfbrained** [comment]
fixed
